name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: Tekgar
  GITHUB_REPOSITORY: classPythonAddike/pycordia
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash
      
      - name: Install requirements
        run: |
          apt-get update
          apt-get -y install git rsync python3-sphinx python3-pip
          python3 -m pip install Sphinx
          python3 -m pip install sphinx-press-theme

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: "chmod +x docs/build.sh && docs/build.sh"
        shell: bash