name: Publish Documentation

env:
  GITHUB_ACTOR: Tekgar
  GITHUB_REPOSITORY: angelCarias/pycordia
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    
      - name: Install packages and clone repo
        run: |
          set -x
          apt-get update
          apt-get -y install git python3-pip
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash
      
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt

      - name: Build docs with Sphinx
        run: |
          make generate_docs
          rm .github examples pycordia -rf
          rm requirements.txt setup.py
          cp docs/_build/html . -r
          rm docs -rf
          mv html docs
        shell: bash
      
      - name: Initialise Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git init
          git remote add deploy "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout -b gh-pages
        shell: bash
      
      - name: Push Docs
        run: |
          touch .nojekyll
          git pull deploy gh-pages
          git add .
          msg="Updating docs for commit ${GITHUB_SHA}"
          git commit -am "${msg}"
          git push deploy gh-pages
        shell: bash
